### PR TITLE
Fix #18:  Tags must not be quoted strings

### LINKED ISSUE #18: Using extended tags corrupts database
Configure the sink to include e.g. "SourceContext" as a tag:
```json
  "sinkOptions": {
    "ExtendedTags": [ "SourceContext" ],
```
Now try to filter data by source context =>
image

All values are shown double-quoted, and we get an error: ` error @5:48-5:55: undefined identifier Program error @5:17-5:55: invalid binary operator <INVALID_OP> error @5:17-5:57: invalid binary operator <INVALID_OP>`

Root cause are the double quotes around the string value. Removing the quotes fixes the problem.

### PR DESCRIPTION
**Pull request by tom-englert**
Fix #18: Using extended tags corrupts database

### CODE REVIEW

**Comment by pada57** [comment]
@tom-englert  can you elaborate bit more. This part was added "recently" do you mean adding a string as ExtendedTags which contains any special characters including double quotes are causing issues ?

then could we use StripSpecialCharacter like https://github.com/pada57/serilog-sinks-influxdb/blob/main/Serilog.Sinks.InfluxDB/Sinks/InfluxDB/InfluxDBSink.cs#L162

to avoid changing the original content of the tag ?

**Comment by tom-englert** [comment]
The quotes aren't part of the original string, they are added by the property serializer.

**Comment by tom-englert** [comment]
The quotes aren't part of the original string, they are added by the property serializer.

**Comment by tom-englert** [comment]
So removing the quotes just restores the original string.

**Comment by tom-englert** [comment]
See also the updated test. Input is  "Stored Value", but output was "\"Stored Value\""

**Comment by tom-englert** [comment]
Superseded by #21

**Pull request closed without merging**
