### PR TITLE
Fix #23: Application- and InstanceName should be optional.

### LINKED ISSUE #23: ApplicationName/InstanceName should be optional
To give more flexibility, `ApplicationName `and `InstanceName` should be optional.

E.g. in our company we need to use `app_name` instead of `appname`, so with optional `ApplicationName` the config would look like this:
```json
"WriteTo": {
  "InfluxDB": {
    "Name": "InfluxDB",
    "Args": {
      "sinkOptions": {
        "ExtendedTags": [ "SourceContext:component_name", "Application:app_name", "Facility:facility" ],
        "ExtendedFields": [ "FacilityCode:facility_code" ],
        "ConnectionInfo": { ... }
      }
    }
  }
},
"Properties": {
  "Application": "MyApplicationName",
  "Facility": "user",
  "FacilityCode": 1
}

```

### PR DESCRIPTION
**Pull request by tom-englert**
Fix #23: Application- and InstanceName should be optional.

### CODE REVIEW

**Comment by pada57** [comment]
@tom-englert  i agree on that statement. was to force being consistent and give "guidance". What you could add to this PR then is having to modify Extensions methods giving more entry point then without "Application" and "Instance" names
what do you think ?

**Comment by tom-englert** [comment]
Not sure which extension methods you are talking about, can you point me to the methods?

**Comment by pada57** [comment]
https://github.com/pada57/serilog-sinks-influxdb/blob/main/Serilog.Sinks.InfluxDB/LoggerConfigurationInfluxDBExtensions.cs

**Comment by tom-englert** [comment]
I don't think these can be changed so easily without loosing backward compatiblity.
But you can always pass `null` for the application name, if you want to override it with some custom logic.

**Comment by tom-englert** [comment]
What could be done is to use the latest c# with nullable enabled and annotate the parameters correctly.

**Comment by tom-englert** [comment]
Any chance to get a release with all PRs until next week?
Anything I can help with?

**Comment by pada57** [comment]
Will work this weekend on it

**Comment by pada57** [comment]
> What could be done is to use the latest c# with nullable enabled and annotate the parameters correctly.

We use DotNet standard which does not allow nullable if not mistaken

**Comment by tom-englert** [comment]
It needs C# 8 or later, however the value for this small interface is not too much.

**Comment by tom-englert** [comment]
> Will work this weekend on it. Which one more urgent?

Only all together will work

**Pull request merged**
